version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Caracas"
    open-pull-requests-limit: 2
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "automated"
      - "dependabot"
    reviewers:
      - "zuccadev"
    allow:
      - dependency-type: "direct"
    groups:
      kotlin-stack:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx*"
          - "app.cash.sqldelight*"
      ktor-stack:
        patterns:
          - "io.ktor*"
      testing-stack:
        patterns:
          - "org.junit*"
          - "io.mockk*"
          - "app.cash.turbine*"
      other-gradle-updates:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "America/Caracas"
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "ci"
      - "automated"
      - "dependabot"
    reviewers:
      - "zuccadev"
    groups:
      github-actions-all:
        patterns:
          - "*"
