package com.applogger.core.model

import com.applogger.core.AppLoggerVersion
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * Immutable representation of a single log event or metric.
 *
 * Created internally by [com.applogger.core.internal.AppLoggerImpl] and queued
 * for transport delivery. All fields are serializable for offline buffering.
 *
 * ## extra field — native type preservation
 * [extra] is `Map<String, JsonElement>?` so that Int, Long, Double, Boolean and String
 * values are stored as native JSON primitives from the moment the event is created.
 * This eliminates the previous String round-trip and the heuristic type-recovery in
 * the transport layer. Supabase JSONB queries work directly:
 * ```sql
 * SELECT * FROM app_logs WHERE (extra->>'retry_count')::int > 2;
 * SELECT * FROM app_logs WHERE (extra->>'is_cached')::boolean = true;
 * ```
 *
 * @property id         Unique event identifier (UUID v4).
 * @property timestamp  Unix epoch millis when the event was created.
 * @property level      Severity level.
 * @property tag        Short source identifier (e.g. class or screen name).
 * @property message    Human-readable description.
 * @property throwableInfo Captured exception info, if any.
 * @property deviceInfo Device metadata snapshot.
 * @property deviceId   Stable device identifier string (SDK-generated by default).
 * @property sessionId  UUID of the current session.
 * @property userId     Optional anonymous user identifier.
 * @property environment Deployment environment (e.g. "production", "staging", "development").
 *                       Set via [com.applogger.core.AppLoggerConfig.Builder.environment].
 * @property extra      Optional key-value metadata. Values are native JSON primitives
 *                      (String, Int, Long, Double, Boolean) — no string conversion.
 * @property sdkVersion SDK semver at event creation time.
 * @property metricName Metric name when level == METRIC.
 * @property metricValue Metric numeric value when level == METRIC.
 * @property metricUnit Metric unit when level == METRIC.
 * @property metricTags Metric contextual tags when level == METRIC. Auto-enriched with
 *                      platform, app_version, device_model by the SDK.
 */
@Serializable
data class LogEvent(
    val id: String,
    val timestamp: Long,
    val level: LogLevel,
    val tag: String,
    val message: String,
    val throwableInfo: ThrowableInfo? = null,
    val deviceInfo: DeviceInfo,
    val deviceId: String = "",
    val sessionId: String,
    val userId: String? = null,
    val environment: String = "production",
    val extra: Map<String, JsonElement>? = null,
    val sdkVersion: String = AppLoggerVersion.NAME,
    // Typed metric fields — only populated when level == METRIC
    val metricName: String? = null,
    val metricValue: Double? = null,
    val metricUnit: String? = null,
    val metricTags: Map<String, String>? = null,
    // Distributed tracing — optionally propagated across devices (mobile → TV gRPC flows).
    // Set via AppLoggerSDK.setTraceId(id). Appears as trace_id column in Supabase.
    val traceId: String? = null,
    // A/B test or experiment variant for this session (from setSessionVariant()).
    val variant: String? = null,
    // Batch integrity ID — assigned by BatchIntegrityManager in Cycle D.
    val batchId: String? = null
)
